version: '3'
services:
    js-utils:
        container_name: js-utils-server
        build: .
        working_dir: /usr/share/nginx/html
        volumes:
            - ./.:/usr/share/nginx/html:delegated
        ports:
            - 80:80
